name: Docker Build and Publish (Reusable)

on:
  workflow_call:
    inputs:
      image-suffix:
        required: false
        type: string
        default: ''
      dockerfile:
        required: false
        type: string
        default: 'Dockerfile'
      image_tags:
        required: false
        type: string
        default: ''

env:
  REGISTRY: ghcr.io
  RACK_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Record commit hash and display version info
        id: commit
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_OUTPUT
          echo ${COMMIT_HASH} > .commit_hash.txt
          echo "Commit hash recorded: ${COMMIT_HASH}"
          head -4 .commit_hash.txt package.json

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
        with:
          platforms: arm64

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3.7.1
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tags: |
            ${{ inputs.image_tags != '' && inputs.image_tags || format('type=ref,event=branch') }}
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}${{ inputs.image-suffix }}
            ${{ github.repository }}${{ inputs.image-suffix }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          annotations: ${{ steps.meta.outputs.annotations }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            COMMIT_HASH=${{ steps.commit.outputs.COMMIT_HASH }}
          # Add this line to include .commit_hash.txt in the build context
          secrets: |
            "commit_hash_file=.commit_hash.txt"
